---
title: "ANOVA mémoire"
author: "GHIRINGHELLI Pierre"
date: "4/29/2022"
output: html_document
---

```{r setup, library}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, library}
library(tidyverse)
library(ggpubr)
library(rstatix)

library(readxl)
Datas <- read_excel("~/Documents/M1 IEAP/Rendus/R niveau 2/Datas.xlsx")
View(Datas)

Data.S1 = filter(Datas, sujet=="1")
Data.S2 = filter(Datas, sujet=="2")
Data.S3 = filter(Datas, sujet=="3")
Data.S4 = filter(Datas, sujet=="4")
Data.S5 = filter(Datas, sujet=="5")
Data.S6 = filter(Datas, sujet=="6")
Data.S7 = filter(Datas, sujet=="7")
#-------------------------------------------------------------------------------
P.5s = filter(Datas, temps.sec=="5")
P.5s.inter = filter(P.5s, interExter=="inter")
P.5s.exter = filter(P.5s, interExter=="exter")
P.5s.course = filter(P.5s, interExter=="course")
P.5s.entrai = filter(P.5s, interExter=="entrai")
#-------------------------------------------------------------------------------
P.15s = filter(Datas, temps.sec=="15")
P.15s.inter = filter(P.15s, interExter=="inter")
P.15s.exter = filter(P.15s, interExter=="exter")
P.15s.course = filter(P.15s, interExter=="course")
P.15s.entrai = filter(P.15s, interExter=="entrai")
#-------------------------------------------------------------------------------
P.30s = filter(Datas, temps.sec=="30")
P.30s.inter = filter(P.30s, interExter=="inter")
P.30s.exter = filter(P.30s, interExter=="exter")
P.30s.course = filter(P.30s, interExter=="course")
P.30s.entrai = filter(P.30s, interExter=="entrai")
#-------------------------------------------------------------------------------
P.5min = filter(Datas, temps.sec=="300")
P.5min.inter = filter(P.5min, interExter=="inter")
P.5min.exter = filter(P.5min, interExter=="exter")
P.5min.course = filter(P.5min, interExter=="course")
P.5min.entrai = filter(P.5min, interExter=="entrai")
#-------------------------------------------------------------------------------
P.20min = filter(Datas, temps.sec=="1200")
P.20min.inter = filter(P.20min, interExter=="inter")
P.20min.exter = filter(P.20min, interExter=="exter")
P.20min.course = filter(P.20min, interExter=="course")
P.20min.entrai = filter(P.20min, interExter=="entrai")
```

```{r - stats}

#----------------------------------MOYENNES-------------------------------------

Moyenne.P.5s.exter = mean(P.5s.exter$puissance.W)
Moyenne.P.5s.inter = mean(P.5s.inter$puissance.W)
Moyenne.P.5s.course = mean(P.5s.course$puissance.W)
Moyenne.P.5s.entrai = mean(P.5s.entrai$puissance.W)
#-------------------------------------------------------------------------------
Moyenne.P.15s.exter = mean(P.15s.exter$puissance.W)
Moyenne.P.15s.inter = mean(P.15s.inter$puissance.W)
Moyenne.P.15s.course = mean(P.15s.course$puissance.W)
Moyenne.P.15s.entrai = mean(P.15s.entrai$puissance.W)
#-------------------------------------------------------------------------------
Moyenne.P.30s.exter = mean(P.30s.exter$puissance.W)
Moyenne.P.30s.inter = mean(P.30s.inter$puissance.W)
Moyenne.P.30s.course = mean(P.30s.course$puissance.W)
Moyenne.P.30s.entrai = mean(P.30s.entrai$puissance.W)
#-------------------------------------------------------------------------------
Moyenne.P.5min.exter = mean(P.5min.exter$puissance.W)
Moyenne.P.5min.inter = mean(P.5min.inter$puissance.W)
Moyenne.P.5min.course = mean(P.5min.course$puissance.W)
Moyenne.P.5min.entrai = mean(P.5min.entrai$puissance.W)
#-------------------------------------------------------------------------------
Moyenne.P.20min.exter = mean(P.20min.exter$puissance.W)
Moyenne.P.20min.inter = mean(P.20min.inter$puissance.W)
Moyenne.P.20min.course = mean(P.20min.course$puissance.W)
Moyenne.P.20min.entrai = mean(P.20min.entrai$puissance.W)

```

```{r}

# Rassembler les colonnes t1, t2 et t3 en format long
# Convertir l'identifiant et le temps en facteurs
selfesteem <- selfesteem %>%
  gather(key = "time", value = "score", t1, t2, t3) %>%
  convert_as_factor(id, time)
head(selfesteem, 3)

# Statistiques descriptives
selfesteem %>%
  group_by(time) %>%
  get_summary_stats(score, type = "mean_sd")

# Visualisation 
bxp <- ggboxplot(selfesteem, x = "time", y = "score", add = "point")
bxp

# Test de Normalité
selfesteem %>%
  group_by(time) %>%
  shapiro_test(score)
ggqqplot(selfesteem, "score", facet.by = "time")

# Calcul
res.aov <- anova_test(data = selfesteem, dv = score, wid = id, within = time)
get_anova_table(res.aov)

# Tests post-hox (t-test comparaison par paires) 
pwc <- selfesteem %>%
  pairwise_t_test(
    score ~ time, paired = TRUE,
    p.adjust.method = "bonferroni"
    )

# Représentation graphique 
pwc <- pwc %>% add_xy_position(x = "time")
bxp + 
  stat_pvalue_manual(pwc) +
  labs(
    subtitle = get_test_label(res.aov, detailed = TRUE),
    caption = get_pwc_label(pwc)
  )

```